language: php

php:
  - 7.3

addons:
  chrome: stable

services:
  - mysql

before_install:
  - mysql -e 'CREATE SCHEMA eugenio_db;'

install:
  - cp .env.travis .env
  - cp phpunit.travis.xml phpunit.xml
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
  - php artisan dusk:chrome-driver

script:
  - vendor/bin/phpunit
  - php artisan dusk
